[API_KEYS]
#OPENAI = ""
#GROQ = ""
#ANTHROPIC = ""
#GEMINI = ""

[API_ENDPOINTS]
OLLAMA = "http://eos.lan:11434"
SEARXNG = "http://searxng.docker.lan:4000"

[GENERAL]
PORT = 3_001
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"
