name: perplexica
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    image: perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng.docker.lan:4000
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://eos.lan:3001/api
        - NEXT_PUBLIC_WS_URL=ws://eos.lan:3001
    image: perplexica-frontend:main
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
